### ISSUE TITLE
입장페이지 디자인

### ISSUE THREAD

**Issue by Jungeun04** [eDanMoo/client#2]
컴포넌트 별로 사용할 수 있게 자세히 만들기

**Comment by sj0917** [comment]
- 왼쪽 화면
- [ ] 단어 비내리는 효과 or 한컴타자연습
- [ ] 한컴타자연습 배경화면 느낌으로

- 오른쪽 화면
- [ ] 로고
- [ ] 입장 코드 입력 칸
- [ ] 입장 버튼
- [ ] 방 만들기 버튼
